### ISSUE TITLE
Port Buildkite Shellwords parser from Go to Dart

### ISSUE THREAD

**Issue by bootstraponline** [software-platform/metrics#57]
The task is to create a standalone Dart port of the shellwords library from Buildkite. Shellwords is useful for parsing strings in the same way as the UNIX Bourne shell. 

> A golang library for splitting command-line strings into words like a Posix or Windows shell would.

https://github.com/buildkite/shellwords

# Tasks
- [ ] Configure the shellwords job on Bitrise. https://app.bitrise.io/app/65e2c5934061cc08
- [x] Port parser https://github.com/buildkite/shellwords/blob/master/parser.go
- [x] Use the right quotes depending on OS https://github.com/buildkite/shellwords/blob/master/quote.go#L8
- [x] Port tests
